const state = {
  frame: 1, mode: "frame", scores: [], players: [], turn: 0,
  redsRemaining: 15, phase: "red", colourIndex: 0, tablePoints: 0,
  history: [], events: [], started: false
};
const COLOURS = [
  { ball: "yellow", points: 2 }, { ball: "green", points: 3 }, { ball: "brown", points: 4 },
  { ball: "blue", points: 5 }, { ball: "pink", points: 6 }, { ball: "black", points: 7 }
];
const $ = id => document.getElementById(id);
const escapeHtml = value => String(value).replace(/[&<>\"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;", "'":"&#39;"}[char]));
function snapshot(){return JSON.parse(JSON.stringify({mode:state.mode,scores:state.scores,players:state.players,turn:state.turn,redsRemaining:state.redsRemaining,phase:state.phase,colourIndex:state.colourIndex,tablePoints:state.tablePoints,history:state.history}));}
function saveEvent(label){state.events.push({label,before:snapshot()});}
function finishTurn(){if(state.tablePoints>0)state.history.unshift({player:state.players[state.turn],points:state.tablePoints});state.tablePoints=0;state.turn=(state.turn+1)%state.players.length;}
function renderPlayerInputs(){const count=Math.max(2,Number($("playerCount").value)||2);$("playerCount").disabled=false;$("playerInputs").innerHTML=Array.from({length:count},(_,i)=>`<label><span>PLAYER ${i+1}</span><input id="playerInput${i}" value="Player ${i+1}" maxlength="24" placeholder="Player name" /></label>`).join("");}
function render(){
  $("frameNumber").textContent=state.frame;
  const formatLabel=$("formatLabel");if(formatLabel)formatLabel.textContent=state.mode==="century"?"OPEN CENTURY • MULTI PLAYER":"BEST OF 7 FRAMES";
  $("modeLabel").textContent=state.mode==="century"?"CENTURY • RED 10 POINTS":"FRAME (7)";
  $("phaseChip").textContent=state.mode==="century"?"CENTURY MODE":"FRAME MODE";
  $("turnIndicator").textContent=(state.players[state.turn]||"PLAYER 1").toUpperCase();$("tablePoints").textContent=state.tablePoints;
  $("sequenceLabel").textContent=state.mode==="century"?"ANY COLOUR • RED = 10 POINTS":state.phase==="red"?"RED":state.phase==="colour"?"COLOUR":`COLOURS ONLY: ${COLOURS[state.colourIndex]?.ball?.toUpperCase()||"COMPLETE"}`;
  $("playersGrid").innerHTML=state.players.map((player,i)=>`<article class="score-card player-card ${state.turn===i?"active":""}" id="playerCard${i}"><div class="player-card-head"><span class="player-symbol">♙</span><span class="player-name">${escapeHtml(player).toUpperCase()}</span><span class="turn-badge ${state.turn===i?"":"waiting"}">${state.turn===i?"AT TABLE":"WAITING"}</span></div><div class="player-score-row"><div class="score">${state.scores[i]||0}</div><div class="player-stats"><span>FRAMES <b>0</b></span><span>BREAK <b>${state.turn===i?state.tablePoints:0}</b></span><span>POINTS <b>${state.scores[i]||0}</b></span></div></div><div class="score-actions"><button class="score-add" data-quick-score="1">+1</button><button class="score-add" data-quick-score="4">+4</button><button class="score-add" data-quick-score="7">+7</button></div><div class="card-actions"><button class="secondary-btn" data-undo="1">↶ UNDO</button><button class="secondary-btn danger-action" data-open-foul="1">⚠ FOUL</button></div><div class="turn-label">${state.turn===i?"YOUR TURN":"WAITING"}</div></article>`).join("");
  document.querySelectorAll(".ball").forEach(btn=>{const ball=btn.dataset.ball;let allowed=false;if(state.mode==="century")allowed=true;else if(state.phase==="red")allowed=ball==="red";else if(state.phase==="colour")allowed=ball!=="red";else if(state.phase==="colours")allowed=ball===COLOURS[state.colourIndex]?.ball;btn.disabled=!allowed;btn.style.opacity=allowed?"1":".35";btn.querySelector("span").textContent=state.mode==="century"&&ball==="red"?"10":btn.dataset.points;});
  $("breakHistory").innerHTML=state.history.length?state.history.map(x=>`<div class="history-item"><span>${escapeHtml(x.player)}</span><strong>${x.points} pts</strong></div>`).join(""):'<div class="subtle">No break recorded yet.</div>';
  document.querySelectorAll("[data-quick-score]").forEach(btn=>btn.disabled=state.turn!==Number(btn.closest(".player-card")?.id.replace("playerCard","")));
}
function startFrame(){state.mode=$("gameMode").value;const count=Math.max(2,Number($("playerCount").value)||2);state.players=Array.from({length:count},(_,i)=>$("playerInput"+i)?.value.trim()||`Player ${i+1}`);state.scores=Array(count).fill(0);state.turn=0;state.frame=1;state.redsRemaining=15;state.phase="red";state.colourIndex=0;state.tablePoints=0;state.history=[];state.events=[];state.started=true;["scoreboard","tableCard","historyCard","controls"].forEach(id=>$(id).classList.remove("hidden"));$("setupCard").classList.add("hidden");$("foulHelp").textContent=state.mode==="century"?"Century mode foul penalty is fixed at 10 points.":"Select a standard foul penalty.";document.querySelectorAll("[data-foul]").forEach(btn=>btn.style.display=state.mode==="century"&&btn.dataset.foul!=="10"?"none":"block");render();}
function scoreBall(ball,points){if(state.mode==="century")points=ball==="red"?10:Number(points);const valid=state.mode==="century"||(state.phase==="red"&&ball==="red")||(state.phase==="colour"&&ball!=="red")||(state.phase==="colours"&&ball===COLOURS[state.colourIndex]?.ball);if(!valid)return;saveEvent(`Scored ${points}`);state.scores[state.turn]+=points;state.tablePoints+=points;if(state.mode!=="century"){if(state.phase==="red"){state.redsRemaining--;state.phase="colour";}else if(state.phase==="colour"){state.phase=state.redsRemaining>0?"red":"colours";if(state.phase==="colours")state.colourIndex=0;}else if(state.phase==="colours"){state.colourIndex++;if(state.colourIndex>=COLOURS.length)state.phase="complete";}}render();}
function quickScore(points){saveEvent(`Quick score ${points}`);state.scores[state.turn]+=points;state.tablePoints+=points;render();}
function switchTurn(){saveEvent("End turn");finishTurn();render();}
function applyFoul(points){if(state.mode==="century")points=10;saveEvent(`Foul ${points}`);state.scores[(state.turn+1)%state.players.length]+=points;finishTurn();$("foulModal").classList.add("hidden");render();}
function undo(){const event=state.events.pop();if(!event)return alert("Nothing to undo.");Object.assign(state,event.before);render();}
function newFrame(){state.frame++;state.scores=Array(state.players.length).fill(0);state.turn=0;state.redsRemaining=15;state.phase="red";state.colourIndex=0;state.tablePoints=0;state.history=[];state.events=[];render();}
function resetMatch(){state.started=false;$("setupCard").classList.remove("hidden");["scoreboard","tableCard","historyCard","controls"].forEach(id=>$(id).classList.add("hidden"));renderPlayerInputs();}
$("gameMode").addEventListener("change",renderPlayerInputs);$("playerCount").addEventListener("change",renderPlayerInputs);
document.addEventListener("click",event=>{const ball=event.target.closest(".ball");if(ball&&!ball.disabled)return scoreBall(ball.dataset.ball,Number(ball.dataset.points));const quick=event.target.closest("[data-quick-score]");if(quick&&!quick.disabled)return quickScore(Number(quick.dataset.quickScore));if(event.target.closest("#startBtn"))return startFrame();if(["missBtn","endFrameBtn","nextTurnBtn"].includes(event.target.id))return switchTurn();if(event.target.id==="undoBtn"||event.target.closest("[data-undo]"))return undo();if(event.target.id==="newFrameBtn")return newFrame();if(["resetMatchBtn","resetCenterBtn"].includes(event.target.id))return resetMatch();if(event.target.id==="foulBtn"||event.target.closest("[data-open-foul]"))return $("foulModal").classList.remove("hidden");if(event.target.id==="cancelFoul")return $("foulModal").classList.add("hidden");const foul=event.target.closest("[data-foul]");if(foul)return applyFoul(Number(foul.dataset.foul));});
renderPlayerInputs();render();