const state={frame:1,mode:'frame',scores:[],players:[],turn:0,redsRemaining:15,phase:'red',colourIndex:0,tablePoints:0,history:[],events:[],started:false};
const COLOURS=[['yellow',2],['green',3],['brown',4],['blue',5],['pink',6],['black',7]];const $=id=>document.getElementById(id);const esc=v=>String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function snap(){return JSON.parse(JSON.stringify({mode:state.mode,scores:state.scores,players:state.players,turn:state.turn,redsRemaining:state.redsRemaining,phase:state.phase,colourIndex:state.colourIndex,tablePoints:state.tablePoints,history:state.history}));}function save(label){state.events.push({label,before:snap()});}function finishTurn(){if(state.tablePoints)state.history.unshift({player:state.players[state.turn],points:state.tablePoints});state.tablePoints=0;state.turn=(state.turn+1)%state.players.length;}
function renderPlayerInputs(){const n=Math.max(2,Number($('playerCount').value)||2);$('playerInputs').innerHTML=Array.from({length:n},(_,i)=>`<label><span>PLAYER ${i+1}</span><input id="playerInput${i}" value="Player ${i+1}" maxlength="24" placeholder="Player name"></label>`).join('');}
function render(){if($('frameNumber'))$('frameNumber').textContent=state.frame;if($('modeLabel'))$('modeLabel').textContent=state.mode==='century'?'CENTURY • RED 10 POINTS':'FRAME (7)';if($('phaseChip'))$('phaseChip').textContent=state.mode==='century'?'CENTURY MODE':'FRAME MODE';if($('turnIndicator'))$('turnIndicator').textContent=(state.players[state.turn]||'PLAYER 1').toUpperCase();const vsPanel=document.querySelector('.vs-panel');if(vsPanel){const miniLabel=vsPanel.querySelector('.mini-label');const frameNumber=$('frameNumber');const vs=vsPanel.querySelector('.vs');const turnIndicator=$('turnIndicator');const century=state.mode==='century';if(miniLabel)miniLabel.textContent=century?'CENTURY':'FRAME';if(frameNumber)frameNumber.style.display=century?'none':'';if(vs)vs.style.display=century?'none':'';if(turnIndicator)turnIndicator.style.display=century?'none':'';}if($('tablePoints'))$('tablePoints').textContent=state.tablePoints;if($('sequenceLabel'))$('sequenceLabel').textContent=state.mode==='century'?'ANY COLOUR • RED = 10 POINTS':state.phase==='red'?'RED':state.phase==='colour'?'COLOUR':`COLOURS ONLY: ${COLOURS[state.colourIndex]?.[0]?.toUpperCase()||'COMPLETE'}`;
if($('playersGrid'))$('playersGrid').innerHTML=state.players.map((p,i)=>`<article class="score-card player-card ${state.turn===i?'active':''}" id="playerCard${i}"><div class="player-card-head"><span class="player-symbol">♙</span><span class="player-name">${esc(p).toUpperCase()}</span><span class="turn-badge ${state.turn===i?'':'waiting'}">${state.turn===i?'AT TABLE':'WAITING'}</span></div><div class="player-score-row"><div class="score">${state.scores[i]||0}</div><div class="player-stats"><span>FRAMES <b>0</b></span><span>BREAK <b>${state.turn===i?state.tablePoints:0}</b></span><span>POINTS <b>${state.scores[i]||0}</b></span></div></div><div class="card-actions"><button class="secondary-btn" data-undo="1">↶ UNDO</button><button class="secondary-btn danger-action" data-open-foul="1">⚠ FOUL</button></div><div class="turn-label">${state.turn===i?'YOUR TURN':'WAITING'}</div></article>`).join('');
 document.querySelectorAll('.ball').forEach(b=>{const ball=b.dataset.ball;const ok=state.mode==='century'||(state.phase==='red'&&ball==='red')||(state.phase==='colour'&&ball!=='red')||(state.phase==='colours'&&ball===COLOURS[state.colourIndex]?.[0]);b.disabled=!ok;b.style.opacity=ok?'1':'.35';b.querySelector('span').textContent=state.mode==='century'&&ball==='red'?'10':b.dataset.points;});if($('breakHistory'))$('breakHistory').innerHTML=state.history.length?state.history.map(x=>`<div class="history-item"><span>${esc(x.player)}</span><strong>${x.points} pts</strong></div>`).join(''):'<div class="subtle">No break recorded yet.</div>';}
function beginMatch(){state.scores=Array(state.players.length).fill(0);state.turn=0;state.frame=1;state.redsRemaining=15;state.phase='red';state.colourIndex=0;state.tablePoints=0;state.history=[];state.events=[];state.started=true;['scoreboard','tableCard','historyCard','controls'].forEach(id=>$(id)?.classList.remove('hidden'));$('setupCard')?.classList.add('hidden');render();}
function startFrame(){state.mode=$('gameMode').value;const n=Math.max(2,Number($('playerCount').value)||2);state.players=Array.from({length:n},(_,i)=>$('playerInput'+i)?.value.trim()||`Player ${i+1}`);beginMatch();}
function scoreBall(ball,points){if(state.mode==='century')points=ball==='red'?10:Number(points);const ok=state.mode==='century'||(state.phase==='red'&&ball==='red')||(state.phase==='colour'&&ball!=='red')||(state.phase==='colours'&&ball===COLOURS[state.colourIndex]?.[0]);if(!ok)return;save('Scored '+points);state.scores[state.turn]+=points;state.tablePoints+=points;if(state.mode!=='century'){if(state.phase==='red'){state.redsRemaining--;state.phase='colour';}else if(state.phase==='colour'){state.phase=state.redsRemaining>0?'red':'colours';if(state.phase==='colours')state.colourIndex=0;}else if(state.phase==='colours'){state.colourIndex++;if(state.colourIndex>=COLOURS.length)state.phase='complete';}}render();}
function quickScore(points){save('Quick score '+points);state.scores[state.turn]+=points;state.tablePoints+=points;render();}function switchTurn(){save('End turn');finishTurn();render();}function applyFoul(points){save('Foul '+points);state.scores[(state.turn+1)%state.players.length]+=points;finishTurn();$('foulModal')?.classList.add('hidden');render();}function undo(){const e=state.events.pop();if(!e)return alert('Nothing to undo.');Object.assign(state,e.before);render();}function newFrame(){state.frame++;state.scores=Array(state.players.length).fill(0);state.turn=0;state.redsRemaining=15;state.phase='red';state.colourIndex=0;state.tablePoints=0;state.history=[];state.events=[];render();}function resetMatch(){state.started=false;$('setupCard')?.classList.remove('hidden');['scoreboard','tableCard','historyCard','controls'].forEach(id=>$(id)?.classList.add('hidden'));renderPlayerInputs();render();}
document.addEventListener('click',e=>{const b=e.target.closest('.ball');if(b&&!b.disabled)return scoreBall(b.dataset.ball,Number(b.dataset.points));if(e.target.closest('#startBtn'))return startFrame();if(['missBtn','endFrameBtn','nextTurnBtn'].includes(e.target.id))return switchTurn();if(e.target.id==='undoBtn'||e.target.closest('[data-undo]'))return undo();if(e.target.id==='newFrameBtn')return newFrame();if(['resetMatchBtn','resetCenterBtn'].includes(e.target.id))return resetMatch();if(e.target.id==='foulBtn'||e.target.closest('[data-open-foul]'))return $('foulModal').classList.remove('hidden');if(e.target.id==='cancelFoul')return $('foulModal').classList.add('hidden');const f=e.target.closest('[data-foul]');if(f)return applyFoul(Number(f.dataset.foul));});
renderPlayerInputs();render();
setTimeout(()=>{const btn=$('centuryModeBtn');if(!btn)return;let names=[];btn.addEventListener('click',()=>{const row=document.querySelector('.player-count-row');if(!row)return;row.innerHTML='<label class="century-label">CENTURY PLAYERS</label><div id="centuryPlayerList" class="century-player-list"></div><div class="century-add-row"><input id="centuryNameInput" maxlength="24" placeholder="Enter player name"><button id="addCenturyPlayer" class="player-count-btn" type="button">+ ADD PLAYER</button></div><p class="century-help">Add multiple players. Red = 10 points. Any colour can be played.</p>';$('playerInputs').innerHTML='';$('startBtn').textContent='START CENTURY →';const list=$('centuryPlayerList');const draw=()=>list.innerHTML=names.map((n,i)=>`<div class="century-player-item"><span>${i+1}. ${esc(n)}</span><button type="button" data-remove-century="${i}">REMOVE</button></div>`).join('')||'<div class="subtle">No players added yet.</div>';const add=()=>{const input=$('centuryNameInput'),n=input.value.trim();if(!n)return;names.push(n);input.value='';draw();};$('addCenturyPlayer').onclick=add;$('centuryNameInput').onkeydown=e=>{if(e.key==='Enter')add();};list.onclick=e=>{const r=e.target.closest('[data-remove-century]');if(r){names.splice(Number(r.dataset.removeCentury),1);draw();}};draw();$('foulHelp').textContent='Century fouls: Red foul = 10 points. Other fouls = 4, 5, 6 or 7 points.';document.querySelectorAll('[data-foul]').forEach(f=>{f.style.display='block';f.textContent=f.dataset.foul==='10'?'RED FOUL • 10':f.dataset.foul;});window.startFrame=()=>{if(!names.length)return alert('Please add at least one player.');state.mode='century';state.players=[...names];beginMatch();};});},0);

document.addEventListener('click',e=>{if(e.target.closest('#startBtn'))setTimeout(()=>{const btn=$('newFrameBtn');if(btn)btn.textContent=state.mode==='century'?'NEW CENTURY':'NEW FRAME';},0);

// Premium HOME button: return from setup or scoring to the main mode-selection page.
function addHomeButton(){const actions=document.querySelector('.top-actions');if(!actions||$('backHomeBtn'))return;const btn=document.createElement('button');btn.id='backHomeBtn';btn.type='button';btn.textContent='⌂ HOME';btn.style.cssText='margin-left:10px;padding:10px 14px;border:1px solid rgba(240,210,127,.55);border-radius:999px;background:rgba(1,7,4,.65);color:#f0d27f;font:900 11px Georgia,serif;letter-spacing:.12em;cursor:pointer;';actions.appendChild(btn);}
function goHome(){if($('scoringApp'))$('scoringApp').classList.add('hidden');if($('landing'))$('landing').classList.remove('hidden');state.started=false;$('setupCard')?.classList.remove('hidden');['scoreboard','tableCard','historyCard','controls'].forEach(id=>$(id)?.classList.add('hidden'));addHomeButton();}
document.addEventListener('click',e=>{if(e.target.closest('#backHomeBtn')){e.preventDefault();goHome();}});setTimeout(addHomeButton,0);});